### ISSUE TITLE
IDE hang with when processing files async

### ISSUE THREAD

**Issue by AB-xdev** [xdev-software/intellij-plugin-save-actions#160]
Option: "Process files asynchronously" is active

IDE hang occur when certain files are formatted (in my case the file is new inside Git):

```
"AWT-EventQueue-0" #64 [15240] prio=6 os_prio=0 cpu=7078.12ms elapsed=32.03s tid=0x000001f77d5163d0 nid=15240 waiting on condition  [0x000000ca272fc000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@21.0.4/Native Method)
        - parking to wait for  <0x000000075a3ab448> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(java.base@21.0.4/LockSupport.java:221)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@21.0.4/AbstractQueuedSynchronizer.java:754)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@21.0.4/AbstractQueuedSynchronizer.java:990)
        at java.util.concurrent.locks.ReentrantLock$Sync.lock(java.base@21.0.4/ReentrantLock.java:153)
        at java.util.concurrent.locks.ReentrantLock.lock(java.base@21.0.4/ReentrantLock.java:322)
        at software.xdev.saveactions.core.service.impl.AbstractSaveActionsService.processPsiFilesIfNecessaryWithLock(AbstractSaveActionsService.java:115)
        at software.xdev.saveactions.core.service.impl.AbstractSaveActionsService.guardedProcessPsiFiles(AbstractSaveActionsService.java:109)
        at software.xdev.saveactions.core.service.impl.SaveActionsJavaService.guardedProcessPsiFiles(SaveActionsJavaService.java:23)
        at software.xdev.saveactions.core.listener.SaveActionsDocumentManagerListener.beforeDocumentsSaving(SaveActionsDocumentManagerListener.java:76)
        at software.xdev.saveactions.core.listener.SaveActionsDocumentManagerListener.beforeAllDocumentsSaving(SaveActionsDocumentManagerListener.java:59)
        at java.lang.invoke.LambdaForm$DMH/0x0000000800620400.invokeInterface(java.base@21.0.4/LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$MH/0x000000080023d000.invoke(java.base@21.0.4/LambdaForm$MH)
        at java.lang.invoke.LambdaForm$MH/0x0000000800891800.invoke_MT(java.base@21.0.4/LambdaForm$MH)
        at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:719)
        at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:682)
        at com.intellij.util.messages.impl.MessageBusImplKt.executeOrAddToQueue(MessageBusImpl.kt:514)
        at com.intellij.util.messages.impl.ToDirectChildrenMessagePublisher.publish$intellij_platform_core(CompositeMessageBus.kt:310)
        at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:471)
        at jdk.proxy2.$Proxy18.beforeAllDocumentsSaving(jdk.proxy2/Unknown Source)
        at java.lang.invoke.LambdaForm$DMH/0x0000000800620400.invokeInterface(java.base@21.0.4/LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$MH/0x0000000800cb8800.invoke(java.base@21.0.4/LambdaForm$MH)
        at java.lang.invoke.Invokers$Holder.invokeExact_MT(java.base@21.0.4/Invokers$Holder)
        at jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.base@21.0.4/DirectMethodHandleAccessor.java:153)
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(java.base@21.0.4/DirectMethodHandleAccessor.java:103)
        at java.lang.reflect.Method.invoke(java.base@21.0.4/Method.java:580)
        at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.multiCast(FileDocumentManagerImpl.java:174)
        at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$new$0(FileDocumentManagerImpl.java:130)
        at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$$Lambda/0x00000008004ab948.invoke(Unknown Source)
        at jdk.proxy2.$Proxy18.beforeAllDocumentsSaving(jdk.proxy2/Unknown Source)
        at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveDocuments(FileDocumentManagerImpl.java:279)
        at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:267)
        at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:260)
        at com.intellij.ide.actions.SaveAllAction.actionPerformed(SaveAllAction.kt:25)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.kt:345)
        at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:32)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$actionProcessor$1.performAction(IdeKeyEventDispatcher.kt:496)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner$lambda$4$lambda$3(IdeKeyEventDispatcher.kt:845)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt$$Lambda/0x00000008026cb168.run(Unknown Source)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner$lambda$4(IdeKeyEventDispatcher.kt:845)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt$$Lambda/0x00000008026cd950.run(Unknown Source)
        at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks(ActionManagerImpl.kt:1164)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.kt:362)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner(IdeKeyEventDispatcher.kt:843)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.access$doPerformActionInner(IdeKeyEventDispatcher.kt:1)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction$intellij_platform_ide_impl(IdeKeyEventDispatcher.kt:572)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.kt:509)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.kt:448)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.kt:441)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.kt:303)
        at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:620)
        at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$15(IdeEventQueue.kt:582)
        at com.intellij.ide.IdeEventQueue$$Lambda/0x0000000802610828.compute(Unknown Source)
        at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:582)
        at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:73)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:357)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:356)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:356)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:351)
        at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke$lambda$0(IdeEventQueue.kt:1035)
        at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1$$Lambda/0x000000080075bba8.run(Unknown Source)
        at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
        at com.intellij.openapi.application.WriteIntentReadAction$$Lambda/0x0000000800764258.compute(Unknown Source)
        at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:910)
        at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
        at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
        at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
        at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
        at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
        at com.intellij.ide.IdeEventQueueKt$$Lambda/0x000000080075b718.run(Unknown Source)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
        at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
        at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$10(IdeEventQueue.kt:351)
        at com.intellij.ide.IdeEventQueue$$Lambda/0x0000000800759dc0.run(Unknown Source)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:397)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop/EventDispatchThread.java:207)
        at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop/EventDispatchThread.java:128)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop/EventDispatchThread.java:117)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop/EventDispatchThread.java:113)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop/EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.run(java.desktop/EventDispatchThread.java:92)

   Locked ownable synchronizers:
        - None
```

Looks like the lock is not released correctly

**Comment by AB-xdev** [comment]
Problem only happens when you have 2 projects open and one of them uses the new option.

If you perform a save (Ctrl + S( it saves both projects in parallel, causing a lock failure as one project locks the UI while the other one tries (which has the lock) tries to aquire the UI thread. Thus causing a deadlock.

```
2024-09-26 17:04:12,425 [ 632385]   FINE - #software.xdev.saveactions.core.service.SaveActionsService - [+] Start SaveActionsDocumentManagerListener#beforeAllDocumentsSaving, vaadin-grid-filter
2024-09-26 17:04:12,425 [ 632385]   FINE - #software.xdev.saveactions.core.service.SaveActionsService - Locating psi files for 1 documents: [DocumentImpl[GridFilterQueryParameterAdapter.java]]
2024-09-26 17:04:12,429 [ 632389]   FINE - #software.xdev.saveactions.core.service.SaveActionsService - End SaveActionsDocumentManagerListener#beforeAllDocumentsSaving
2024-09-26 17:04:12,429 [ 632389]   FINE - #software.xdev.saveactions.core.service.SaveActionsService - [+] Start SaveActionsDocumentManagerListener#beforeAllDocumentsSaving, intellij-plugin-save-actions
2024-09-26 17:04:12,429 [ 632389]  FINER - #software.xdev.saveactions.core.service.SaveActionsService - Getting lock
2024-09-26 17:04:12,429 [ 632389]  FINER - #software.xdev.saveactions.core.service.SaveActionsService - Got lock
2024-09-26 17:04:12,429 [ 632389]   INFO - #software.xdev.saveactions.core.service.SaveActionsService - Processing Project(name=vaadin-grid-filter, containerState=COMPONENT_CREATED, componentStore=D:\_repos\github-xdev\vaadin-grid-filter) files [PsiJavaFile:GridFilterQueryParameterAdapter.java] mode saveAll
2024-09-26 17:04:12,429 [ 632389]   FINE - #software.xdev.saveactions.core.service.SaveActionsService - Locating psi files for 1 documents: [DocumentImpl[GridFilterQueryParameterAdapter.java]]
2024-09-26 17:04:12,429 [ 632389]  FINER - #software.xdev.saveactions.core.service.SaveActionsService - Getting lock
2024-09-26 17:04:12,440 [ 632400]   INFO - #software.xdev.saveactions.core.service.SaveActionsService - Valid files [PsiJavaFile:GridFilterQueryParameterAdapter.java]
2024-09-26 17:04:12,440 [ 632400]   INFO - #software.xdev.saveactions.core.service.SaveActionsService - Start processors (25)
2024-09-26 17:04:12,440 [ 632400]   INFO - #software.xdev.saveactions.core.service.SaveActionsService - Filtered processors [fieldCanBeFinal, localCanBeFinal, localCanBeFinalExceptImplicit, unqualifiedFieldAccess, unqualifiedMethodAccess, missingOverrideAnnotation, explicitTypeCanBeDiamond, unnecessarySemicolon, organizeImports, reformatChangedCode]
2024-09-26 17:04:12,440 [ 632400]   INFO - #software.xdev.saveactions.core.service.SaveActionsService - Flushing files (1)
```

**Comment by AB-xdev** [comment]
Snapshot confirms that this fixes the problem. Preparing release
