### ISSUE TITLE
IDEA 2024.1 reports error in plugin

### ISSUE THREAD

**Issue by rehdie** [xdev-software/intellij-plugin-save-actions#95]
IntelliJ IDEA 2024.1 reports the following problem:

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'software.xdev.saveactions.core.action.ToggleAnAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: software.xdev.saveactions]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

Used plugin version: 1.2.0 (the latest version when this issue was created)

**Comment by rehdie** [comment]
wow, this was fixed amazingly fast, thx.
